#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_Arabian.out
#PBS -e $PBS_JOBID.bcftools_view_Arabian.err
#PBS -N bcftools_view_Arabian.pbs
#PBS -q small
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

#bcftools view -S Arabian_ids.list thesis_intersect.vcf.gz > thesis_intersect_Arabian.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_Arabian.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_Arabian.vcf.gz
bcftools view thesis_intersect_Arabian.vcf.gz --min-af 0.05 > thesis_intersect_Arabian_AF_over_0.05.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_Arabian_AF_over_0.05.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_Arabian_AF_over_0.05.vcf.gz
bcftools view thesis_intersect_Arabian.vcf.gz --max-af 0.005 > thesis_intersect_Arabian_AF_less_than_0.005.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_Arabian_AF_less_than_0.005.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_Arabian_AF_less_than_0.005.vcf.gz
