#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=1g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.Extract_variants_Morgan_rare_pop_common_shared_shared.out
#PBS -e $PBS_JOBID.Extract_variants_Morgan_rare_pop_common_shared_shared.err
#PBS -N Extract_variants_Morgan_rare_pop_common_shared_shared.pbs
#PBS -q batch
module load bcftools
cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_pop_rare_common_vcfs/breed_pop_rare_common_chrom_pos/../breed_pop_rare_common_snpeff
bcftools view -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_pop_rare_common_vcfs/breed_pop_rare_common_chrom_pos/Morgan_rare_pop_common_shared.txt /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/SnpEff/thesis_intersect_snpeff.ann.vcf.gz > Morgan_rare_pop_common_shared_shared_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip Morgan_rare_pop_common_shared_shared_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix Morgan_rare_pop_common_shared_shared_snpeff.vcf.gz
