#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=1g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.Extract_variants_unique_variants_Clydesdale_unique_unique.out
#PBS -e $PBS_JOBID.Extract_variants_unique_variants_Clydesdale_unique_unique.err
#PBS -N Extract_variants_unique_variants_Clydesdale_unique_unique.pbs
#PBS -q batch
module load bcftools
cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_pop_rare_common_vcfs/breed_pop_rare_common_chrom_pos/../breed_pop_rare_common_snpeff
bcftools view -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_pop_rare_common_vcfs/breed_pop_rare_common_chrom_pos/unique_variants_Clydesdale_unique.txt /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/SnpEff/thesis_intersect_snpeff.ann.vcf.gz > unique_variants_Clydesdale_unique_unique_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip unique_variants_Clydesdale_unique_unique_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix unique_variants_Clydesdale_unique_unique_snpeff.vcf.gz
