#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_Shetland.out
#PBS -e $PBS_JOBID.bcftools_view_Shetland.err
#PBS -N bcftools_view_Shetland.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools isec -p Shetland_rare_Arabian_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_Arabian_common.vcf.gz
bcftools isec -p Shetland_rare_Belgian_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_Belgian_common.vcf.gz
bcftools isec -p Shetland_rare_Clydesdale_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_Clydesdale_common.vcf.gz
bcftools isec -p Shetland_rare_Icelandic_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_Icelandic_common.vcf.gz
bcftools isec -p Shetland_rare_Morgan_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_Morgan_common.vcf.gz
bcftools isec -p Shetland_rare_QH_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_QH_common.vcf.gz
bcftools isec -p Shetland_rare_STB_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_STB_common.vcf.gz
bcftools isec -p Shetland_rare_TB_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_TB_common.vcf.gz
bcftools isec -p Shetland_rare_WP_common thesis_intersect_Shetland_rare.vcf.gz thesis_intersect_WP_common.vcf.gz
