#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=1g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.Extract_variants_Arabian_rare_WP_common.out
#PBS -e $PBS_JOBID.Extract_variants_Arabian_rare_WP_common.err
#PBS -N Extract_variants_Arabian_rare_WP_common.pbs
#PBS -q batch
module load bcftools
cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs/breed_rare_common_chrom_pos/../breed_rare_common_snpeff
bcftools view -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs/breed_rare_common_chrom_pos/Arabian_rare_WP_common.txt /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/SnpEff/thesis_intersect_snpeff.ann.vcf.gz > Arabian_rare_WP_common_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip Arabian_rare_WP_common_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix Arabian_rare_WP_common_snpeff.vcf.gz
