#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=06:00:00,mem=1g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.Extract_variants_TB_rare_Belgian_common.out
#PBS -e $PBS_JOBID.Extract_variants_TB_rare_Belgian_common.err
#PBS -N Extract_variants_TB_rare_Belgian_common.pbs
#PBS -q batch
module load bcftools
cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs/breed_rare_common_chrom_pos/../breed_rare_common_snpeff
bcftools view -R /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_rare_common_vcfs/breed_rare_common_chrom_pos/TB_rare_Belgian_common.txt /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/SnpEff/thesis_intersect_snpeff.ann.vcf.gz > TB_rare_Belgian_common_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip TB_rare_Belgian_common_snpeff.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix TB_rare_Belgian_common_snpeff.vcf.gz
