#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=06:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_stats_by_ind.out
#PBS -e $PBS_JOBID.bcftools_stats_by_ind.err
#PBS -N bcftools_stats_by_ind.pbs
#PBS -q small
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools stats -s SRR2142311 thesis_intersect.vcf.gz > SRR2142311_Other.stats
