#!/bin/bash -l
#SBATCH --job-name=VEP.slurm
#SBATCH --nodes=1 #specify one node
#SBATCH --ntasks=1
#SBATCH --time=24:00:00 
#SBATCH --ntasks=2 
#SBATCH --mem=10g 
#SBATCH --mail-type=FAIL 
#SBATCH --mail-user=durwa004@umn.edu 
#SBATCH -A durwa004 
#SBATCH -e VEP.%j.e 
#SBATCH -o VEP.%j.o 

conda activate ensembl-vep

cd /home/durwa004/durwa004/genetic_burden/

#filter_vep --format vcf -i joint_genotype_combined.goldenPath.vep.vcf --filter "(IMPACT = HIGH) or (IMPACT = MODERATE) or (IMPACT = LOW)" -o joint_genotype_combined.goldenPath.vep.hml.vcf --force_overwrite
gunzip joint_genotype.goldenPath.vep.subset.vcf.gz 
filter_vep --format vcf -i joint_genotype.goldenPath.vep.subset.vcf --filter "(IMPACT = HIGH) or (IMPACT = MODERATE) or (IMPACT = LOW)" -o joint_genotype.vep.subset.hml.vcf --force_overwrite
#--gtf /home/durwa004/shared/VEPDocs/Equus_caballus.EquCab3.0.103_genomic.nice.gtf --fasta /home/durwa004/shared/VEPDocs/goldenPath.Ec_build-3.0_wMSY.fa  --vcf --force_overwrite

bgzip joint_genotype.vep.subset.hml.vcf
tabix joint_genotype.vep.subset.hml.vcf.gz 
bgzip joint_genotype.goldenPath.vep.subset.vcf
tabix joint_genotype.goldenPath.vep.subset.vcf.gz


