#!/bin/bash -l
#SBATCH --job-name=VEP.slurm
#SBATCH --nodes=1 #specify one node
#SBATCH --ntasks=1
#SBATCH --time=24:00:00 
#SBATCH --ntasks=2 
#SBATCH --mem=10g 
#SBATCH --mail-type=FAIL 
#SBATCH --mail-user=durwa004@umn.edu 
#SBATCH -A durwa004 
#SBATCH -e VEP.%j.e 
#SBATCH -o VEP.%j.o 

conda activate ensembl-vep

cd /home/durwa004/durwa004/genetic_burden/

vep --format vcf -i joint_genotype_combined.goldenPath.vep.hml.vcf.gz --plugin Loftool.pm -o joint_genotype_combined.goldenPath.vep.hml.LOF.vcf.gz --force_overwrite --gtf /home/durwa004/shared/VEPDocs/Equus_caballus.EquCab3.0.103_genomic.nice.gtf.gz --fasta /home/durwa004/shared/VEPDocs/goldenPath.Ec_build-3.0_wMSY.fa  --vcf --force_overwrite

