#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=24:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.ANNOVAR_variant_type_NC_009165_3.out
#PBS -e $PBS_JOBID.ANNOVAR_variant_type_NC_009165_3.err
#PBS -N ANNOVAR_variant_type_NC_009165_3.pbs
#PBS -q small
source /home/mccuem/shared/.local/conda/bin/activate snakemake

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect/annovar/annovar_variant_function_by_chr

python /home/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/genetic_burden/python_scripts/extract_annovar_variants_all.py -c NC_009165_3
