#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isec_Shetland_pop.out
#PBS -e $PBS_JOBID.bcftools_isec_Shetland_pop.err
#PBS -N bcftools_isec_Shetland_pop.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_pop_rare_common_vcfs

bcftools isec -p Shetland_rare_pop_common ../breed_rare_common_vcfs/Shetland_rare.vcf.gz without_Shetland_common.vcf.gz
bcftools isec -p Shetland_common_pop_rare ../breed_rare_common_vcfs/Shetland_common.vcf.gz without_Shetland_rare.vcf.gz
bcftools isec -p unique_variants_Shetland ../thesis_intersect_Shetland.vcf.gz thesis_intersect_without_Shetland.vcf.gz
