#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_isec_QH_pop.out
#PBS -e $PBS_JOBID.bcftools_isec_QH_pop.err
#PBS -N bcftools_isec_QH_pop.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/breed_intersect_files/breed_pop_rare_common_vcfs

bcftools isec -p QH_rare_pop_common ../breed_rare_common_vcfs/QH_rare.vcf.gz thesis_intersect_without_QH_common.vcf.gz
bcftools isec -p QH_common_pop_rare ../breed_rare_common_vcfs/QH_common.vcf.gz thesis_intersect_without_QH_rare.vcf.gz
bcftools isec -p unique_variants_QH ../thesis_intersect_QH.vcf.gz thesis_intersect_without_QH.vcf.gz
