#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 13 14:35:43 2019

@author: durwa004
"""

#Merge in bcfstats by AF column
import pandas as pd
import os

path = "/Users/durwa004/Documents/PhD/Projects/1000_genomes/GB_project/bcftools_stats_output/AF_freq_files/"
tmp_df = pd.DataFrame()
AF = []
with open(path + "/LIPI0187A_Other_AF_freq.txt") as tmp_file:
    tmp_file.readline()
    for line in tmp_file:
        line = line.rstrip("\n").split("\t")
        AF.append(line[0])
    tmp_df['AF'] = AF
        
for filename in os.listdir(path):
    a = filename.split("_")
    b = a[0] + "_" + a[1]
    freq = []
    with open(path + "/" + filename, "r") as input_file:
        input_file.readline()
        for line in input_file:
            line = line.rstrip("\n").split("\t")
            freq.append(line[1])
        tmp_df[b] = freq
    
tmp_df.to_csv(path + "/../all_horses_AF_freq_info.txt", sep='\t', index=False)

#t_tmp_df.to_csv(path + "/../all_horses_AF_freq_info_transposed.txt", sep='\t', index=False)
#Get number of singletons
t_tmp_df = tmp_df.transpose()
t_tmp_df['M411_QH']

#Can't figure out the pandas df way of manipulating this!

with open(path + "/../all_horses_AF_freq_info_transposed.txt", "r") as input_file, open(path + "/../10_breeds_singletons.txt","w") as output_file:
    input_file.readline()
    for line in input_file:
        line = line.rstrip("\n").split("\t")
        if "Other" in line[0]:
            next
        else:
            breed = 
            print(line[0], file = output_file)
#Then look at output file in R
            


with open(path + "/../all_horses_AF_freq_info.txt", "r") as input_file, open(path + "../all_horses_AF_categorized.txt", "w") as output_file:
    header = input_file.readline()
    header = header.rstrip("\n").split("\t")
    print("\t".join(header),file = output_file)
    for line in input_file:
        line = line.rstrip("\n").split("\t")
        AF = float(line[0])
        if AF < 1:
            print("<1%","\t", "\t".join(line[1:]), file = output_file, sep = "")
        elif AF >=1 and AF < 5:
            print("1-<5%","\t", "\t".join(line[1:]), file = output_file, sep = "")
        elif AF >=5 and AF < 10:
            print("5-<10%","\t", "\t".join(line[1:]), file = output_file, sep = "")
        elif AF >=10 and AF < 25:
            print("10-<25%","\t", "\t".join(line[1:]), file = output_file, sep = "")
        elif AF >=25 and AF < 50:
            print("25-<50%","\t", "\t".join(line[1:]), file = output_file, sep = "")
        elif AF >=50 and AF < 75:
            print("50-<75%","\t", "\t".join(line[1:]), file = output_file, sep = "")
        elif AF >=75 and AF < 100:
            print("75-<100%","\t", "\t".join(line[1:]), file = output_file, sep = "")
            
        