#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  9 05:01:00 2019

@author: durwa004
"""

import os

directory = "/Users/durwa004/Documents/PhD/Projects/1000_genomes/GB_project/breed_pop_variants/"

chrom_pos = []
breed = []
AC = []
AF = []
MA = []
for filename in os.listdir(directory):
    if filename.endswith("_rare_pop.txt"):
        print(filename)
        with open(directory + "/" + filename, "r") as input_file:
            a = filename.split("_")
            input_file.readline()
            for line in input_file:
                line = line.rstrip("\n").split()
                if "NC_" in line[2]:
                    ab = line[2] + ":" + line[3]
                    chrom_pos.append(ab)
                    breed.append(line[1])
                    AC.append(line[4])
                    AF.append(line[5])
                    MA.append(line[6])

len(chrom_pos) #1770
len(set(chrom_pos)) #1770

with open(directory + "/" + "common_breed_rare_pop_shared_variants.txt", "w") as output_file:
    for i in range(len(chrom_pos)):
        a = chrom_pos[i].split(":")
        print(a[0], a[1], breed[i],AC[i],AF[i],MA[i],sep = "\t", file = output_file)



chrom_pos = list("chrom_pos")
breed_etc = list("breed_etc")
for filename in os.listdir(directory):
    if filename.endswith("_common_pop.txt"):
        print(filename)
        with open(directory + "/" + filename, "r") as input_file:
            a = filename.split("_")
            input_file.readline()
            for line in input_file:
                line = line.rstrip("\n").split()
                if "NC_" in line[2]:
                    ab = line[2] + ":" + line[3]
                    cd = line[1] + ":" + line[4] + ":" + line[5] + ":" + line[6]
                    ac = line[1] + ":" + line[4] 
                    for i,v in enumerate(chrom_pos):
                        if ab == v:
                            bd = breed_etc[i] + ":" + ac
                            breed_etc[i] = bd
                        else:
                            chrom_pos.append(ab)
                            breed_etc.append(cd)


len(chrom_pos) #194,903
len(set(chrom_pos)) #119,586

#Get unique list:
rare_breed = list(set(chrom_pos))
for i,v in enumerate(breed_etc):
    a = v.split(":")
    ab = a[0] + ":" + a[1]
    for item, value in enumerate(rare_breed):
        if ab == 
        

with open(directory + "/" + "rare_breed_common_pop_shared_variants.txt", "w") as output_file:
    for i in range(len(rare_breed)):
        a = rare_breed[i].split(":")
        print(a[0], a[1], sep = "\t", file = output_file)

#Add in breed        
chrom_pos = []
for filename in os.listdir(directory):
    if filename.endswith("_common_pop.txt"):
        print(filename)
        with open(directory + "/" + filename, "r") as input_file:
            a = filename.split("_")
            input_file.readline()
            for line in input_file:
                line = line.rstrip("\n").split()
                if "NC_" in line[2]:
                    ab = line[2] + ":" + line[3]
                    for i,v in enumerate(rare_breed):
                        if ab == v:
                            bc = ab + ":" + line[1] 
                            chrom_pos.append(bc)

len(chrom_pos) #194,903
len(set(chrom_pos)) #119,586

rare_breed = list(set(chrom_pos))

with open(directory + "/" + "rare_breed_common_pop_shared_variants_with_breed.txt", "w") as output_file:
    for i in range(len(rare_breed)):
        a = rare_breed[i].split(":")
        print(a[0], a[1], sep = "\t", file = output_file)