#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  9 05:01:00 2019

@author: durwa004
"""

import os

directory = "/Users/durwa004/Documents/PhD/Projects/1000_genomes/GB_project/breed_pop_variants/"

chrom_pos = []
breed = []
AC = []
AF = []
MA = []
for filename in os.listdir(directory):
    if filename.endswith("_rare_pop.txt"):
        print(filename)
        with open(directory + "/" + filename, "r") as input_file:
            a = filename.split("_")
            input_file.readline()
            for line in input_file:
                line = line.rstrip("\n").split()
                if "NC_" in line[2]:
                    ab = line[2] + ":" + line[3]
                    chrom_pos.append(ab)
                    breed.append(line[1])
                    AC.append(line[4])
                    AF.append(line[5])
                    MA.append(line[6])

len(chrom_pos) #1770
len(set(chrom_pos)) #1770

with open(directory + "/" + "common_breed_rare_pop_shared_variants.txt", "w") as output_file:
    for i in range(len(chrom_pos)):
        a = chrom_pos[i].split(":")
        print(a[0], a[1], breed[i],AC[i],AF[i],MA[i],sep = "\t", file = output_file)



rare_breed = {}
for filename in os.listdir(directory):
    if filename.endswith("_common_pop.txt"):
        print(filename)
        with open(directory + "/" + filename, "r") as input_file:
            a = filename.split("_")
            input_file.readline()
            for line in input_file:
                line = line.rstrip("\n").split()
                if "NC_" in line[2]:
                    ab = line[2] + ":" + line[3]
                    cd = line[1] + ":" + line[4] + ":" + line[5] + ":" + line[6]
                    ac = line[1] + ":" + line[4]
                    if ab in rare_breed.keys():
                        ef = rare_breed[ab]
                        rare_breed[ab] = ef + ":" + ac
                    else:
                        rare_breed[ab] = cd

len(set(rare_breed)) #119,586


with open(directory + "/" + "rare_breed_common_pop_shared_variants.txt", "w") as output_file:
    for key,value in rare_breed.items():
        a = key.split(":")
        b = value.split(":")
        print("\t".join(a),"\t".join(b), sep = "\t", file = output_file)
