#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_STB_mx_AC_3.out
#PBS -e $PBS_JOBID.bcftools_view_STB_mx_AC_3.err
#PBS -N bcftools_view_STB_mx_AC_3.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools view --max-ac 3 --exclude AF<0.05 thesis_intersect_STB.vcf.gz > rare_STB_common_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip rare_STB_common_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix rare_STB_common_population.vcf.gz
bcftools view --min-ac 5 --exclude AF>0.02 thesis_intersect_STB.vcf.gz > common_STB_rare_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip common_STB_rare_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix common_STB_rare_population.vcf.gz
