#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_Arabian_mx_AC_2.out
#PBS -e $PBS_JOBID.bcftools_view_Arabian_mx_AC_2.err
#PBS -N bcftools_view_Arabian_mx_AC_2.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools view --max-ac 2 --min-af 0.05 thesis_intersect_Arabian.vcf.gz > rare_Arabian_common_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip rare_Arabian_common_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix rare_Arabian_common_population.vcf.gz
bcftools view --min-ac 4 --max-af 0.005 thesis_intersect_Arabian.vcf.gz > common_Arabian_rare_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip common_Arabian_rare_population.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix common_Arabian_rare_population.vcf.gz
