#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=2g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_WP.out
#PBS -e $PBS_JOBID.bcftools_view_WP.err
#PBS -N bcftools_view_WP.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools view -S WP_ids.list --min-ac 1 thesis_intersect.vcf.gz > thesis_intersect_WP.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_WP.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_WP.vcf.gz
bcftools view thesis_intersect_WP.vcf.gz --min-ac 1 --max-ac 1 > thesis_intersect_WP_rare.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_WP_rare.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_WP_rare.vcf.gz
bcftools view thesis_intersect_WP.vcf.gz --min-ac 4 > thesis_intersect_WP_common.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_WP_common.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_WP_common.vcf.gz
