#!/bin/bash -l
#PBS -l nodes=1:ppn=12,walltime=48:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_Arabian.out
#PBS -e $PBS_JOBID.bcftools_view_Arabian.err
#PBS -N bcftools_view_Arabian.pbs
#PBS -q small
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools view -S Arabian_ids.list --min-ac 1 thesis_intersect.vcf.gz > thesis_intersect_Arabian.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_Arabian.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_Arabian.vcf.gz
bcftools view thesis_intersect_Arabian.vcf.gz --min-ac 1 --max-ac 2 > thesis_intersect_Arabian_rare.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_Arabian_rare.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_Arabian_rare.vcf.gz
bcftools view thesis_intersect_Arabian.vcf.gz --min-ac 7 > thesis_intersect_Arabian_common.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_intersect_Arabian_common.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_intersect_Arabian_common.vcf.gz
