qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_QH.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_Arabian.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_WP.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_Icelandic.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_Morgan.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_Clydesdale.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_Belgian.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_STB.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_TB.pbs
qsub /panfs/roc/groups/3/mccuem/shared/Projects/HorseGenomeProject/scripts/EquCab3/genetic_burden_pipeline/split_by_breed/bcftools_view_Shetland.pbs
