#!/bin/bash -l
#PBS -l nodes=1:ppn=8,walltime=12:00:00,mem=4g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.bcftools_view_Shetland.out
#PBS -e $PBS_JOBID.bcftools_view_Shetland.err
#PBS -N bcftools_view_Shetland.pbs
#PBS -q batch
module load bcftools

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/joint_intersect

bcftools view --min-ac 6 thesis_intersect_Shetland.vcf.gz > common_Shetland_over_AF_0.05.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip common_Shetland_over_AF_0.05.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix common_Shetland_over_AF_0.05.vcf.gz
