#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=21:00:00,mem=10g
#PBS -m abe
#PBS -M durwa004@umn.edu
#PBS -o $PBS_JOBID.SnpEff_intersect.out
#PBS -e $PBS_JOBID.SnpEff_intersect.err
#PBS -N SnpEff_intersect.pbs
#PBS -q small 

cd /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/ibio_output_files/joint_gvcf/SnpEff/RAPGEF5/

java -Djava.io.tmpdir=/home/mccuem/shared/Projects/HorseGenomeProject/Data/temp_files -Xmx4g -jar /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/snpEff.jar -C /home/mccuem/shared/Projects/HorseGenomeProject/Data/ibio_EquCab3/variant_annotation/SnpEff/snpEff/snpEff.config Mansour.EquCab2 thesis_union_NC_009147.3.gz > thesis_union_RAPGEF5_Mansour.ann.vcf -csvstats thesis_union_RAPGEF5_Mansour.csv -stats ../SnpEff/thesis_union_RAPGEF5_Mansour.html &&/home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/bgzip thesis_union_RAPGEF5_Mansour.ann.vcf && /home/mccuem/durwa004/.conda/envs/ensembl-vep/bin/tabix thesis_union_RAPGEF5_Mansour.ann.vcf.gz
